Repository jzhupan/tech-jobs, pull requests merged in 2024-03, with the labels that each got.

#10 Removed default styling
  src/App.css
  src/App.jsx
  src/index.css
  src/main.jsx
Labels: UI, Removal

#15 Added a simple Appbar from MUI components as a placeholder for now.
  src/App.css
  src/App.jsx
  src/components/common/Navbar.jsx
Labels: enhancement, UI

#18 made cities and countries more concise
  src/data/mock-up.json
Labels: enhancement, Data, Addition

#24 Tested mock-up data to populate table
  package-lock.json
  package.json
  src/App.jsx
  src/components/common/EnhancedTable.jsx
Labels: enhancement, UI

#31 UI/footer
  src/App.css
  src/App.jsx
  src/components/common/Footer.jsx
Labels: enhancement, UI, Addition

#32 Cleaned up the navigation bar.
  src/components/common/Navbar.jsx
Labels: enhancement, UI, Removal

#38 Accomplished URL disable feature, tested with mockup JSON file
  src/components/common/EnhancedTable.jsx
Labels: enhancement, UI, Addition

#42 UI - Hiring Locations
  src/components/common/EnhancedTable.jsx
  src/data/companies.json
Labels: UI, Removal

#43 Added missing information for cgi company in the JSON file.
  src/data/companies.json
Labels: Bug, enhancement, Data

#45 Removed hiring locations from companies.json
  src/data/companies.json
Labels: Data, Removal

#48 Removed Hiring locations column and Country based column.
  src/components/common/EnhancedTable.jsx
Labels: UI, Removal
